### ISSUE TITLE
Debian and Mac OS support?

### ISSUE THREAD

**Issue by YongtaoS** [Dash-Industry-Forum/ISOSegmentValidator#21]
Does the validator support building on Debian and Mac OS?

To make the source be compilable on MacOX, I changed the Makefile with the following two lines:

```
#compatibility= -m32 -static-libstdc++
 compatibility= -arch x86_64 -static-libstdc++ -std=c++11

 #CC=     $(shell which g++)
 CC= /usr/local/bin/g++-8
```

Then I test ValidateMP4 with a cmaf mp4. It returns errors:

`./bin/Assemble 1 ~/temp/v00-0.mp4 ~/temp/v00-1.mp4 ~/temp/v00-2.mp4 ~/temp/v00-3.mp4 `

`./bin/ValidateMP4 -infofile segmentSizeInfoFile.txt -cmaf tempMerged.mp4 `
> < ! -- Source file is 'tempMerged.mp4' -->
> "###" error:  
> "###"        No 'ftyp' atoms
> "###" error:  
> "###"        No 'moov' atoms
> "###" error:  
> "###"        CMAF check violated: Section 7.3.1. "CMAF Header SHALL include one MovieBox.", found 0 'moov' box

However, the file actually contains ftyp and moov, as verified by iso viewer. Why do these errors occur?

I guess errors are due to the build environment, what are the build environment for the source? When I build it on Debian, it also pops up many warnings and errors, e.g.
```
../src/ValidateAtoms.cpp:2406:1: warning: jump to label ‘bail’ [-fpermissive]
 bail:
 ^
In file included from ../src/ValidateAtoms.cpp:21:0:
../src/ValidateMP4.h:976:68: warning:   from here [-fpermissive]
 #define BAILIFERR( statement ) do { err = statement; if (err) goto bail; } while (false)
                                                                    ^
../src/ValidateAtoms.cpp:2205:2: note: in expansion of macro ‘BAILIFERR’
  BAILIFERR( GetFileData( aoe, &vsdi, offset, (UInt64)fieldOffset(VideoSampleDescriptionInfo,extensions) /* sizeof(vsdi) */, &offset ) );
  ^
../src/ValidateAtoms.cpp:2214:7: error:   crosses initialization of ‘char vsdi_name [strlen(((const char*)(& vsdi.VideoSampleDescriptionInfo::name)))]’
  char vsdi_name[strlen(vsdi.name)];
       ^
```
And I appreciate much if you could tell me how to solve those errors on Debian and/or Mac.

Thank you for any tips!

**Comment by Hkalpa** [comment]
This happens when ftyp is actually pytf and moov is voom
Probably you have to specify -DLITTLEENDIAN flag when compile

**Comment by SeawardT** [comment]
I am seeing a similar issue. However, Makefile already has the little endian flag.


compiling object file "obj/ValidateDolby.o" ...
../src/ValidateDolby.cpp: In function ‘OSErr Validate_lac4_Atom(atomOffsetEntry*, void*)’:
../src/ValidateDolby.cpp:255:1: error: jump to label ‘bail’
  255 | bail:
      | ^~~~
In file included from ../src/ValidateDolby.cpp:21:
../src/ValidateMP4.h:1012:10: note:   from here
 1012 |     goto bail; \
      |          ^~~~
../src/ValidateDolby.cpp:246:69: note: in expansion of macro ‘GOTOBAIL’
  246 |     UInt32 reserved_shall_be_zero = GetBits(&bb, 7, &err); if (err) GOTOBAIL;
      |                                                                     ^~~~~~~~
../src/ValidateDolby.cpp:250:12: note:   crosses initialization of ‘UInt32 num_presentation_labels’
  250 |     UInt32 num_presentation_labels = GetBits(&bb, 9, &err); if (err) GOTOBAIL;
      |            ^~~~~~~~~~~~~~~~~~~~~~~
../src/ValidateDolby.cpp:255:1: error: jump to label ‘bail’
  255 | bail:
      | ^~~~

**Comment by eceozturk** [comment]
The validator is not supported on MacOS/Debian and it also stopped supporting Windows. The used environment is Linux Ubuntu. For further information on the setup environment, you can also check the [installation guide](https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/blob/master/Doc/Conformance%20Software%20Installation%20Guide.pdf).

**Comment by SeawardT** [comment]
Ill open a separate issue about building against Ubuntu. I was referring to Debian and Ubuntu as the same.

**Comment by SeawardT** [comment]
Confirmed that this does build on Ubuntu 18, but not Debian. Ill look into see if I can make Debian supported.
