### ISSUE TITLE
Warning for ISO/IEC 14496-12 ImageDescription name must be '0' not '10'

### ISSUE THREAD

**Issue by koln67** [Dash-Industry-Forum/ISOSegmentValidator#28]
The following conformance warning shows up from the segment validator.

../src/ValidateAtoms.cpp : 2298 : Warning for ISO/IEC 14496-12 ImageDescription name must be '0' not '10'

However, according to the ISO/IEC 14496-12 section 12.1.3.3: Compressorname is a name, for informative purposes. It is formatted in a fixed 32‐byte field, with the first byte set to the number of bytes to be displayed, followed by that number of bytes of displayable data, and then padding to complete 32 bytes total (including the size byte). The field may be set to 0.        

The spec seems to say that the field for ImageDescription name may be set to 0, but does not have to be set to 0. Is this an error in the segment validator, which checks that the ImageDescription name must be the hard coded value 0?

**Comment by RodolpheFouquet** [comment]
Hi, thanks for reporting the issue, I'll start working on this next week (I'm on a long week-end leave for French national day).

**Comment by koln67** [comment]
Thanks

**Comment by RodolpheFouquet** [comment]
Well, yeah, there even is a comment about it: https://github.com/Dash-Industry-Forum/ISOSegmentValidator/blob/677843b990334e1314f5fb9c8c499694b2b91a4d/public/src/ValidateAtoms.cpp#L2298

xD

**Comment by koln67** [comment]
I guess I worded my question incorrectly. What I meant was

Why is 0 the only acceptable value for ImageDescription name? According to the spec, the field can be 0, but the spec does not say it must be 0. I think this line should be removed, or at least changed to be a more lenient check. 

	"FieldMustBe( vsdi.name[0], 0, "ImageDescription name must be '%d' not '%d'" );"

**Comment by RodolpheFouquet** [comment]
IT shouldn't be, above this line, there is a comment to check the string.

Instead of that, the size should be taken, and then, the string should be check.

**Comment by RodolpheFouquet** [comment]
I've pushed a fix, I'll report on this once I've pushed an update to the server
