### ISSUE TITLE
Warning for ISO/IEC 14496-12 SoundDescription numChannels must be 2 not 1

### ISSUE THREAD

**Issue by koln67** [Dash-Industry-Forum/ISOSegmentValidator#29]
The following warning message sometimes appears when the ISOSegmentValidator is run.

../src/ValidateAtoms.cpp : 3478 : Warning for ISO/IEC 14496-12 SoundDescription numChannels must be 2 not 1

However, according to the ISO/IEC 14496-12 spec, section 12.2.3.1, ChannelCount is a value greater than zero that indicates the
maximum number of channels that the audio could deliver. A ChannelCount of 1 indicates mono audio, and
2 indicates stereo (left/right). When values greater than 2 are used, the codec configuration should identify the
channel assignment.

While the conformance checker code checks that the numChannels is 2, the spec suggests that the numChannels can either be 2 or 1, and that a value of 1 may also be correct in some cases. It seems like line 3478 should be changed, allowing numChannels to equal 1 if the audio is mono. 

	"FieldMustBe( ssdi.numChannels, 2, "SoundDescription numChannels must be %d not %d" );"

**Comment by RodolpheFouquet** [comment]
Ok, the description seems to be a bit more specific than that:

if ChannelCount 1 or 2, no check required.
If above 2, you also need to check that all the channels are assigned.

Does that make sense?

I'm pushing an update that fixes your issue, but I need to add the additional checks for the channel layout.

**Comment by RodolpheFouquet** [comment]
Well, I'll close that once the update is pushed to the server (I'll bundle a release with a bunch of other issues)
