### ISSUE TITLE
AC-4 assets are tested against wrong requirements

### ISSUE THREAD

**Issue by wschidol** [Dash-Industry-Forum/ISOSegmentValidator#40]
We are testing conformance on https://ott.dolby.com/User/wshao/AC-4_Kit_v1.5/DASH/OnDemand/MPD/Multi_Lang_720p_2997fps_h264.mpd , checking the "segment validation" and "DASH-IF". Amongst others, the tool comes back with the error message 

###        ETSI_TS_102_366_V1.4.1 Annex F Line  12729: Track timescale 240000 not equal to the (integer part of) the Sample entry sample rate 48000.0

Note the reference to ETSI_TS_102_366 which defines E-AC-3, not AC-4. So the wrong requirements are asserted.

**Comment by wschidol** [comment]
In git commit b2e16d6, https://github.com/Dash-Industry-Forum/ISOSegmentValidator/blob/master/public/src/ValidateAtoms.cpp lines 3445ff read

```
    if (vg.dolby && (ssdi.sampleSize != 16))
    {
        errprint("ETSI TS 103 190-2 v1.2.1 Annex E Line  00013976: sampleSize shall be set to 16 but is %d\n", ssdi.sampleSize );
    }

    sampleratelo = (ssdi.sampleRate) & 0xFFFF;
    sampleratehi = (ssdi.sampleRate >> 16) & 0xFFFF;

    if (vg.dolby && (sampleratehi != tir->mediaTimeScale)) {
        errprint("ETSI_TS_102_366_V1.4.1 Annex F Line  12729: Track timescale %d not equal to the (integer part of) the Sample entry sample rate %d.%d\n",
                tir->mediaTimeScale, sampleratehi, sampleratelo);
        }
    atomprint(">\n"); //vg.tabcnt++;
```
Clearly, the same condition `if(vg.dolby)` is used to trigger tests for AC-4 as well as for EAC-3. `vg.dolby` is a global variable that is set from the command line, which likewise only contains a single command line switch, -dolby. Therefore, the ISOBMFF validator is simply not set up to distinguish between both data types. This is however necessary since the codecs are governed by different specs and requirements.

**Comment by RodolpheFouquet** [comment]
Hi, understood, AC4, and EAC-3 need to be considered separately, the since they have different validation requirements.

I'll keep you updated.

**Comment by yanj-github** [comment]
@RodolpheFouquet  Thanks for the acknowledgment I will generate the pull request once the fix is done and tested.

**Comment by yanj-github** [comment]
Pull request made to fix this issue as follows: 
https://github.com/Dash-Industry-Forum/DASH/pull/39
https://github.com/Dash-Industry-Forum/ISOSegmentValidator/pull/41
